### PR TITLE
Add stepper motor

### PR DESCRIPTION
**Pull request by jscoobyced**
Add a stepper motor with configurable pin names
image

### CODE REVIEW

**Comment by jscoobyced** [comment]
WIP, need to fix/add connectors.

**Comment by CedricAgoda** [comment]
@SamuelFisher any comment on this PR? I would like to have it (it's from my other GH, open-source account)

**Comment by jscoobyced** [comment]
> @SamuelFisher any comment on this PR? I would like to have it (it's from my other GH, open-source account)

This is indeed my account :) Hopefully can merge this component if not issue

**Comment by SamuelFisher** [comment]
There  were some problems with the following which I have changed:

1. Special characters were being used to render the line under the "M". This should be a path instead.
2. Pins 1 and 3 were not aligned to the 10x10 grid so it would not have been possible to connect any other components.
3. There are some problems with the text position when displayed vertically. I have set `<option>HorizontalOnly</option>` to prevent this.

Please let me know if you are unhappy with these changes. Otherwise this can be merged.

**Comment by jscoobyced** [comment]
Thank you! That's great, happy of the change!

**Pull request merged**
