### PR TITLE
Added Raspberry Pi A+ / B+, 2 and Zero GPIO

### PR DESCRIPTION
**Pull request by kopiro**

### CODE REVIEW

**Comment by SamuelFisher** [comment]
Thanks for adding this. It looks like the last row of pins (`GND` and `GPIO21`) are outside the container rectangle - could you make the container slightly bigger so they are inside?

preview

**Comment by kopiro** [comment]
Done!

**Comment by kopiro** [comment]
Can I use in the web editor now ? :D

**Comment by SamuelFisher** [comment]
I have added it to the web editor now, as "Raspberry Pi 2/Zero".

**Pull request merged**
