### PR TITLE
4510 BCD Counter

### PR DESCRIPTION
**Pull request by Corsaka**
Essentially, a more advanced version of a 4-bit counter. It allows for pre-loading inputs and a few other options such as terminal count, clock enable, and up or down counting.

Perhaps an inclusion of a 4511 Decoder may be worth it, but I don't really see any plausible gain from it compared to pre-loading.

If you need a datasheet for it, you can find one [here,](https://www.engineersgarage.com/electronic-components/4510-ic) and if required I can also move components around and make it look prettier in order to fit in better with the CD aesthetic. This is basically a placeholder so I know whether to put more time into it or not.

### CODE REVIEW

**Comment by Corsaka** [comment]
If required, I can move around the outputs a bit more in order to make it work better with the other parts.

**Comment by SamuelFisher** [comment]
Looks good, thanks for submitting this. The bottom pins are missing connections - would you be able to add those? See below:

image

**Comment by Corsaka** [comment]
Yeah, I'll get that done some point today.

**Comment by Corsaka** [comment]
Should be fixed now.

**Pull request merged**
